spring.application.name=pruebaTecnicaBackend

# H2 DB Config
spring.datasource.url=jdbc:h2:mem:prebadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method


sendgrid.api.key=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
sendgrid.from.email=jfrancogp02@gmail.com

server.port=8080